# Generated by Django 5.1.6 on 2025-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
